-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-01-30 17:28:15 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Beleska 
    ( 
     IDB    NUMBER  NOT NULL , 
     SADRZ  VARCHAR2 (100) , 
     DATZAP DATE 
    ) 
;

ALTER TABLE Beleska 
    ADD CONSTRAINT Beleska_PK PRIMARY KEY ( IDB ) ;

CREATE TABLE Budzetski_plan 
    ( 
     IDPL    NUMBER  NOT NULL , 
     NAZPL   VARCHAR2 (25) , 
     BUDZ    NUMBER , 
     DATPOC  DATE , 
     DATKRAJ DATE 
    ) 
;

ALTER TABLE Budzetski_plan 
    ADD CONSTRAINT Budzetski_plan_PK PRIMARY KEY ( IDPL ) ;

CREATE TABLE Dv_trans 
    ( 
     IDTR           NUMBER  NOT NULL , 
     IDDV           NUMBER  NOT NULL , 
     VRSTADV        VARCHAR2 (25) , 
     STATUSDV       VARCHAR2 (25) , 
     Provizija_IDPR NUMBER 
    ) 
;

ALTER TABLE Dv_trans 
    ADD 
    CHECK (VRSTADV IN ('debitna', 'kreditna')) 
;

ALTER TABLE Dv_trans 
    ADD 
    CHECK (STATUSDV IN ('neuspesna', 'uspesna')) 
;

ALTER TABLE Dv_trans 
    ADD CONSTRAINT Dv_trans_PK PRIMARY KEY ( IDTR ) ;

ALTER TABLE Dv_trans 
    ADD CONSTRAINT Dv_trans_PKv1 UNIQUE ( IDDV ) ;

CREATE TABLE Evidencija 
    ( 
     IZNEV            NUMBER , 
     Beleska_IDB      NUMBER  NOT NULL , 
     Stednja_IDST     NUMBER  NOT NULL , 
     Transakcija_IDTR NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Evidencija__IDX ON Evidencija 
    ( 
     Stednja_IDST ASC 
    ) 
;
CREATE UNIQUE INDEX Evidencija__IDXv1 ON Evidencija 
    ( 
     Beleska_IDB ASC 
    ) 
;

CREATE TABLE Kategorija 
    ( 
     IDKAT               NUMBER  NOT NULL , 
     NAZKAT              VARCHAR2 (25) , 
     TIPKAT              VARCHAR2 (25) , 
     Kategorija_IDKAT    NUMBER  NOT NULL , 
     Budzetski_plan_IDPL NUMBER , 
     Stednja_IDST        NUMBER 
    ) 
;

ALTER TABLE Kategorija 
    ADD 
    CHECK (TIPKAT IN ('prihod', 'rashod')) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_PK PRIMARY KEY ( IDKAT ) ;

CREATE TABLE Kurs 
    ( 
     IDK           NUMBER  NOT NULL , 
     OSV           VARCHAR2 (20) , 
     VRED          NUMBER , 
     DATK          DATE , 
     Valuta_IDVAL2 NUMBER  NOT NULL , 
     Valuta_IDVAL  NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Kurs 
    ADD CONSTRAINT Kurs_PK PRIMARY KEY ( IDK ) ;

CREATE TABLE Podsetnik 
    ( 
     IDPOD   NUMBER  NOT NULL , 
     NAZPOD  VARCHAR2 (25) , 
     DATPOD  DATE , 
     OPISPOD VARCHAR2 (50) 
    ) 
;

ALTER TABLE Podsetnik 
    ADD CONSTRAINT Podsetnik_PK PRIMARY KEY ( IDPOD ) ;

CREATE TABLE Pon_trans 
    ( 
     IDTR            NUMBER  NOT NULL , 
     IDPON           NUMBER  NOT NULL , 
     PERIODPON       VARCHAR2 (20) , 
     DATPOC          DATE , 
     DATZAV          DATE , 
     Podsetnik_IDPOD NUMBER 
    ) 
;

ALTER TABLE Pon_trans 
    ADD CONSTRAINT Pon_trans_PK PRIMARY KEY ( IDTR ) ;

ALTER TABLE Pon_trans 
    ADD CONSTRAINT Pon_trans_PKv1 UNIQUE ( IDPON ) ;

CREATE TABLE Provizija 
    ( 
     IDPR  NUMBER  NOT NULL , 
     IZNPR NUMBER , 
     DATPR DATE , 
     TIPPR VARCHAR2 (20) 
    ) 
;

ALTER TABLE Provizija 
    ADD CONSTRAINT Provizija_PK PRIMARY KEY ( IDPR ) ;

CREATE TABLE Racun 
    ( 
     IDRAC            NUMBER  NOT NULL , 
     NAZRAC           VARCHAR2 (50)  NOT NULL , 
     STANJE           NUMBER  NOT NULL , 
     DATOTV           DATE  NOT NULL , 
     DATZATV          DATE , 
     STATUSRAC        VARCHAR2 (25) , 
     Tip_racuna_IDTIP NUMBER  NOT NULL , 
     Valuta_IDVAL     NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Racun 
    ADD 
    CHECK (STATUSRAC IN ('aktivan', 'blokiran', 'zatvoren')) 
;

ALTER TABLE Racun 
    ADD CONSTRAINT Racun_PK PRIMARY KEY ( IDRAC, Tip_racuna_IDTIP, Valuta_IDVAL ) ;

CREATE TABLE Stednja 
    ( 
     IDST    NUMBER  NOT NULL , 
     IZNC    NUMBER , 
     NAZC    VARCHAR2 (25) , 
     TRENIZN NUMBER 
    ) 
;

ALTER TABLE Stednja 
    ADD CONSTRAINT Stednja_PK PRIMARY KEY ( IDST ) ;

CREATE TABLE Tip_racuna 
    ( 
     IDTIP   NUMBER  NOT NULL , 
     NAZTIP  VARCHAR2 (25)  NOT NULL , 
     OPISTIP VARCHAR2 (100) , 
     MINIZN  NUMBER , 
     LIMIT   NUMBER 
    ) 
;

ALTER TABLE Tip_racuna 
    ADD CONSTRAINT Tip_racuna_PK PRIMARY KEY ( IDTIP ) ;

CREATE TABLE Transakcija 
    ( 
     IDTR                   NUMBER  NOT NULL , 
     OPISTR                 VARCHAR2 (50) , 
     IZNOV                  NUMBER , 
     DATTR                  DATE , 
     IZNTR                  NUMBER , 
     TIPTR                  VARCHAR2 (25)  NOT NULL , 
     Racun_IDRAC            NUMBER  NOT NULL , 
     Racun_Tip_racuna_IDTIP NUMBER  NOT NULL , 
     Racun_Valuta_IDVAL     NUMBER  NOT NULL , 
     Kategorija_IDKAT       NUMBER 
    ) 
;

ALTER TABLE Transakcija 
    ADD CONSTRAINT CH_INH_Transakcija 
    CHECK (TIPTR IN ('Dv_trans', 'Pon_trans', 'Transakcija')) 
;

ALTER TABLE Transakcija 
    ADD CONSTRAINT Transakcija_PK PRIMARY KEY ( IDTR ) ;

CREATE TABLE Valuta 
    ( 
     IDVAL  NUMBER  NOT NULL , 
     NAZVAL VARCHAR2 (20) , 
     DRZ    VARCHAR2 (30) , 
     KOD    VARCHAR2 (5) 
    ) 
;

ALTER TABLE Valuta 
    ADD CONSTRAINT Valuta_PK PRIMARY KEY ( IDVAL ) ;

ALTER TABLE Dv_trans 
    ADD CONSTRAINT Dv_trans_Provizija_FK FOREIGN KEY 
    ( 
     Provizija_IDPR
    ) 
    REFERENCES Provizija 
    ( 
     IDPR
    ) 
;

ALTER TABLE Dv_trans 
    ADD CONSTRAINT Dv_trans_Transakcija_FK FOREIGN KEY 
    ( 
     IDTR
    ) 
    REFERENCES Transakcija 
    ( 
     IDTR
    ) 
;

ALTER TABLE Evidencija 
    ADD CONSTRAINT Evidencija_Beleska_FK FOREIGN KEY 
    ( 
     Beleska_IDB
    ) 
    REFERENCES Beleska 
    ( 
     IDB
    ) 
;

ALTER TABLE Evidencija 
    ADD CONSTRAINT Evidencija_Stednja_FK FOREIGN KEY 
    ( 
     Stednja_IDST
    ) 
    REFERENCES Stednja 
    ( 
     IDST
    ) 
;

ALTER TABLE Evidencija 
    ADD CONSTRAINT Evidencija_Transakcija_FK FOREIGN KEY 
    ( 
     Transakcija_IDTR
    ) 
    REFERENCES Transakcija 
    ( 
     IDTR
    ) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_Budzetski_plan_FK FOREIGN KEY 
    ( 
     Budzetski_plan_IDPL
    ) 
    REFERENCES Budzetski_plan 
    ( 
     IDPL
    ) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_Kategorija_FK FOREIGN KEY 
    ( 
     Kategorija_IDKAT
    ) 
    REFERENCES Kategorija 
    ( 
     IDKAT
    ) 
;

ALTER TABLE Kategorija 
    ADD CONSTRAINT Kategorija_Stednja_FK FOREIGN KEY 
    ( 
     Stednja_IDST
    ) 
    REFERENCES Stednja 
    ( 
     IDST
    ) 
;

ALTER TABLE Kurs 
    ADD CONSTRAINT Kurs_Valuta_FK FOREIGN KEY 
    ( 
     Valuta_IDVAL
    ) 
    REFERENCES Valuta 
    ( 
     IDVAL
    ) 
;

ALTER TABLE Kurs 
    ADD CONSTRAINT Kurs_Valuta_FKv2 FOREIGN KEY 
    ( 
     Valuta_IDVAL2
    ) 
    REFERENCES Valuta 
    ( 
     IDVAL
    ) 
;

ALTER TABLE Pon_trans 
    ADD CONSTRAINT Pon_trans_Podsetnik_FK FOREIGN KEY 
    ( 
     Podsetnik_IDPOD
    ) 
    REFERENCES Podsetnik 
    ( 
     IDPOD
    ) 
;

ALTER TABLE Pon_trans 
    ADD CONSTRAINT Pon_trans_Transakcija_FK FOREIGN KEY 
    ( 
     IDTR
    ) 
    REFERENCES Transakcija 
    ( 
     IDTR
    ) 
;

ALTER TABLE Racun 
    ADD CONSTRAINT Racun_Tip_racuna_FK FOREIGN KEY 
    ( 
     Tip_racuna_IDTIP
    ) 
    REFERENCES Tip_racuna 
    ( 
     IDTIP
    ) 
;

ALTER TABLE Racun 
    ADD CONSTRAINT Racun_Valuta_FK FOREIGN KEY 
    ( 
     Valuta_IDVAL
    ) 
    REFERENCES Valuta 
    ( 
     IDVAL
    ) 
;

ALTER TABLE Transakcija 
    ADD CONSTRAINT Transakcija_Kategorija_FK FOREIGN KEY 
    ( 
     Kategorija_IDKAT
    ) 
    REFERENCES Kategorija 
    ( 
     IDKAT
    ) 
;

ALTER TABLE Transakcija 
    ADD CONSTRAINT Transakcija_Racun_FK FOREIGN KEY 
    ( 
     Racun_IDRAC,
     Racun_Tip_racuna_IDTIP,
     Racun_Valuta_IDVAL
    ) 
    REFERENCES Racun 
    ( 
     IDRAC,
     Tip_racuna_IDTIP,
     Valuta_IDVAL
    ) 
;

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Dv_trans 
BEFORE INSERT OR UPDATE OF IDTR 
ON Dv_trans 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (25); 
BEGIN 
    SELECT A.TIPTR INTO d 
    FROM Transakcija A 
    WHERE A.IDTR = :new.IDTR; 
    IF (d IS NULL OR d <> 'Dv_trans') THEN 
        raise_application_error(-20223,'FK Dv_trans_Transakcija_FK in Table Dv_trans violates Arc constraint on Table Transakcija - discriminator column TIPTR doesn''t have value ''Dv_trans'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_FKArc_1_Pon_trans 
BEFORE INSERT OR UPDATE OF IDTR 
ON Pon_trans 
FOR EACH ROW 
DECLARE 
    d VARCHAR2 (25); 
BEGIN 
    SELECT A.TIPTR INTO d 
    FROM Transakcija A 
    WHERE A.IDTR = :new.IDTR; 
    IF (d IS NULL OR d <> 'Pon_trans') THEN 
        raise_application_error(-20223,'FK Pon_trans_Transakcija_FK in Table Pon_trans violates Arc constraint on Table Transakcija - discriminator column TIPTR doesn''t have value ''Pon_trans'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             2
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


